server:
  port: 9090

spring:
  application:
    name: spring-cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

    servicecomb:
      discovery:
        enabled: true
        address: https://cse.cn-south-1.myhuaweicloud.com
        appName: discovery
        serviceName: spring-cloud-gateway-service
        version: 0.0.1
        watch: false
      config:
        serverAddr: https://cse.cn-south-1.myhuaweicloud.com
        watch:
          delay: 10000
      credentials:
        enabled: true
        accessKey: your access key
        secretKey: your secret key
        akskCustomCipher: default
        project: cn-south-1